name: Release course material to GitHub Releases

on:
  push:
    tags:
      - '*'

# Sets permissions of the GITHUB_TOKEN to allow release to GitHub Releases
permissions:
  contents: write

jobs:
  build-and-release-course-material:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Delete files that should not be released
        run: |
          rm --recursive 00-evaluation-and-exam-archives
          rm --recursive 99-material-for-the-teaching-staff

      - name: Build presentation content with Marp
        uses: docker://marpteam/marp-cli:v3.0.2
        with:
          entrypoint: sh
          args: .github/workflows/build-presentation-content.sh

      - name: Build course material content with Pandoc and weasyprint
        uses: docker://pandoc/minimal:3.1
        with:
          entrypoint: sh
          args: .github/workflows/build-course-material-content.sh

      - name: Release course material to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          body: |
            This release contains the course material for the DAI course at [HEIG-VD](https://heig-vd.ch), Switzerland.
          files: |
            **/*.pdf
